/**
 * Board app API — a single Cloudflare Worker.
 *
 * Boards live in KV as JSON, one key per board, plus an `index` key listing
 * them all. Images live in a second KV namespace and are immutable once
 * written — see NOTES.md for why KV rather than the R2 the spec names.
 *
 * Every route requires `Authorization: Bearer <SHARED_SECRET>`. There is one
 * user, so there is one secret and no accounts.
 */

// Ids are generated by the client as `prefix_random`. Validating them here
// keeps arbitrary strings out of KV keys and R2 object paths.
const ID_RE = /^[a-z]+_[A-Za-z0-9]{1,40}$/;

const INDEX_KEY = "index";

// Images never change once uploaded, so they can be cached hard.
const IMAGE_CACHE = "public, max-age=31536000, immutable";

// KV's hard ceiling on a single value is 25 MiB. The client downscales to
// 1280px WebP long before this, so hitting it means the client failed to.
const IMAGE_MAX_BYTES = 25 * 1024 * 1024;

export default {
  async fetch(request, env) {
    if (request.method === "OPTIONS") return withCors(new Response(null, { status: 204 }));

    let response;
    try {
      response = await route(request, env);
    } catch (err) {
      response = json({ error: "internal", detail: String((err && err.message) || err) }, 500);
    }
    return withCors(response);
  },
};

async function route(request, env) {
  if (!(await authorised(request, env))) {
    return json({ error: "unauthorised" }, 401);
  }

  const url = new URL(request.url);
  const parts = url.pathname.split("/").filter(Boolean); // ["board", "b_home"]
  const [collection, id] = parts;

  if (parts.length === 1 && collection === INDEX_KEY && request.method === "GET") {
    return getIndex(env);
  }

  if (parts.length === 2 && ID_RE.test(id)) {
    if (collection === "board") {
      if (request.method === "GET") return getBoard(env, id);
      if (request.method === "PUT") return putBoard(request, env, id, url);
      if (request.method === "DELETE") return deleteBoard(env, id);
    }
    if (collection === "image") {
      if (request.method === "GET") return getImage(env, id);
      if (request.method === "PUT") return putImage(request, env, id);
    }
  }

  return json({ error: "not_found" }, 404);
}

/* ---------------------------------------------------------------- auth --- */

async function authorised(request, env) {
  // Trimmed because the secret is set by pasting, and a stray newline or space
  // is never a deliberate part of it. Without this a trailing "\n" from however
  // it was piped in produces a length mismatch and a baffling 401.
  const secret = (env.SHARED_SECRET || "").trim();
  if (!secret) return false;

  const header = request.headers.get("authorization") || "";
  const match = /^Bearer (.+)$/.exec(header);
  if (!match) return false;

  const given = new TextEncoder().encode(match[1]);
  const expected = new TextEncoder().encode(secret);

  // timingSafeEqual throws on a length mismatch, so check that separately.
  // The length of the secret is not itself a useful thing to leak.
  if (given.byteLength !== expected.byteLength) return false;
  return crypto.subtle.timingSafeEqual(given, expected);
}

/* -------------------------------------------------------------- boards --- */

async function getBoard(env, id) {
  const stored = await env.BOARDS.get(boardKey(id));
  if (stored === null) return json({ error: "not_found" }, 404);
  return new Response(stored, { headers: jsonHeaders() });
}

/**
 * Last-write-wins with a guard.
 *
 * The client sends the board including the `lastModified` it originally
 * loaded. If the stored copy has moved on since then, another device saved in
 * the meantime and we refuse with 409 rather than clobbering it. The client
 * offers "Reload theirs" or "Keep mine"; "Keep mine" retries with ?force=1.
 */
async function putBoard(request, env, id, url) {
  let board;
  try {
    board = await request.json();
  } catch {
    return json({ error: "bad_json" }, 400);
  }

  const invalid = validateBoard(board, id);
  if (invalid) return json({ error: "invalid_board", detail: invalid }, 400);

  const force = url.searchParams.get("force") === "1";
  const existing = await readBoard(env, id);

  if (!force && existing && existing.lastModified > (board.lastModified || 0)) {
    return json(
      {
        error: "conflict",
        serverLastModified: existing.lastModified,
        yourLastModified: board.lastModified || 0,
      },
      409
    );
  }

  const lastModified = Date.now();
  const saved = { ...board, id, lastModified };

  await env.BOARDS.put(boardKey(id), JSON.stringify(saved));
  await updateIndex(env, (boards) => {
    const rest = boards.filter((b) => b.id !== id);
    rest.push({ id, title: saved.title, lastModified });
    return rest;
  });

  return json({ lastModified });
}

async function deleteBoard(env, id) {
  await env.BOARDS.delete(boardKey(id));
  await updateIndex(env, (boards) => boards.filter((b) => b.id !== id));
  return json({ deleted: id });
}

async function readBoard(env, id) {
  const stored = await env.BOARDS.get(boardKey(id), "json");
  return stored || null;
}

const boardKey = (id) => `board:${id}`;

function validateBoard(board, id) {
  if (!board || typeof board !== "object" || Array.isArray(board)) return "not an object";
  if (typeof board.title !== "string") return "title must be a string";
  if (!Array.isArray(board.cards)) return "cards must be an array";
  if (board.id !== undefined && board.id !== id) return "id does not match the URL";
  return null;
}

/* --------------------------------------------------------------- index --- */

async function getIndex(env) {
  const boards = await readIndex(env);
  return json({ boards });
}

async function readIndex(env) {
  const stored = await env.BOARDS.get(INDEX_KEY, "json");
  return stored && Array.isArray(stored.boards) ? stored.boards : [];
}

/**
 * Read-modify-write. Safe here only because there is one user and writes are
 * debounced — two devices saving different boards within KV's propagation
 * window could drop an index entry. The board itself is never lost, and the
 * next save of that board repairs the index.
 */
async function updateIndex(env, mutate) {
  const boards = mutate(await readIndex(env));
  boards.sort((a, b) => b.lastModified - a.lastModified);
  await env.BOARDS.put(INDEX_KEY, JSON.stringify({ boards }));
}

/* -------------------------------------------------------------- images --- */

async function getImage(env, id) {
  const { value, metadata } = await env.IMAGES.getWithMetadata(id, "arrayBuffer");
  if (value === null) return json({ error: "not_found" }, 404);

  return new Response(value, {
    headers: {
      "content-type": (metadata && metadata.contentType) || "application/octet-stream",
      "cache-control": IMAGE_CACHE,
    },
  });
}

async function putImage(request, env, id) {
  const contentType = request.headers.get("content-type") || "";
  if (!contentType.startsWith("image/")) {
    return json({ error: "not_an_image", detail: contentType || "(none)" }, 400);
  }

  // Images are immutable, so an existing key means this is a retry.
  if ((await env.IMAGES.get(id, "stream")) !== null) return json({ id, existed: true });

  // Buffer rather than stream: KV needs the length up front, and we have to
  // check it against the value limit anyway.
  const body = await request.arrayBuffer();
  if (body.byteLength > IMAGE_MAX_BYTES) {
    return json({ error: "too_large", bytes: body.byteLength, limit: IMAGE_MAX_BYTES }, 413);
  }

  await env.IMAGES.put(id, body, { metadata: { contentType } });
  return json({ id, existed: false, bytes: body.byteLength });
}

/* --------------------------------------------------------------- plumb --- */

function jsonHeaders() {
  return { "content-type": "application/json; charset=utf-8" };
}

function json(body, status = 200) {
  return new Response(JSON.stringify(body), { status, headers: jsonHeaders() });
}

/**
 * The Pages site and the Worker are different origins, so the browser needs
 * these on every response. `*` is fine because the bearer secret is what
 * actually guards the data — a page that does not have it cannot read
 * anything, and we never authenticate with cookies.
 */
function withCors(response) {
  const headers = new Headers(response.headers);
  headers.set("access-control-allow-origin", "*");
  headers.set("access-control-allow-methods", "GET, PUT, DELETE, OPTIONS");
  headers.set("access-control-allow-headers", "authorization, content-type");
  headers.set("access-control-max-age", "86400");
  return new Response(response.body, { status: response.status, headers });
}
